version: 2

project_name: tentacular

before:
  hooks:
    - go mod tidy

snapshot:
  version_template: "{{ incpatch .Version }}-next"

gomod:
  proxy: true

builds:
  - id: tntc
    main: ./cmd/tntc
    binary: tntc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/randybias/tentacular/pkg/version.Version={{.Version}}
      - -X github.com/randybias/tentacular/pkg/version.Commit={{.Commit}}
      - -X github.com/randybias/tentacular/pkg/version.Date={{.CommitDate}}

archives:
  - format: binary
    name_template: "tntc_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: randybias
    name: tentacular
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"
  extra_files:
    - glob: stable.txt

changelog:
  sort: asc
  use: github
  format: "{{ .SHA }}: {{ .Message }}"
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: "Other"
      order: 999
