name: sep-tracker
version: "1.0"
description: "Track MCP SEP proposals from GitHub PRs, diff changes, generate HTML reports, store to Postgres, notify Slack"

deployment:
  namespace: pd-sep-tracker

triggers:
  - type: manual
  - type: cron
    name: weekly-sunday
    schedule: "0 20 * * 0"

nodes:
  fetch-seps:
    path: ./nodes/fetch-seps.ts
  diff-seps:
    path: ./nodes/diff-seps.ts
  render-html:
    path: ./nodes/render-html.ts
  store-report:
    path: ./nodes/store-report.ts
  notify:
    path: ./nodes/notify.ts

edges:
  - from: fetch-seps
    to: diff-seps
  - from: diff-seps
    to: render-html
  - from: fetch-seps
    to: render-html
  - from: fetch-seps
    to: store-report
  - from: render-html
    to: store-report
  - from: diff-seps
    to: store-report
  - from: store-report
    to: notify
  - from: diff-seps
    to: notify

config:
  timeout: 120s
  retries: 1
  target_repo: "modelcontextprotocol/specification"
  sep_label: "sep"

contract:
  version: "1"
  dependencies:
    github:
      protocol: https
      host: api.github.com
      port: 443
      auth:
        type: bearer-token
        secret: github.token
    postgres:
      protocol: postgresql
      host: postgres-postgresql.postgres.svc.cluster.local
      port: 5432
      database: appdb
      user: postgres
      auth:
        type: password
        secret: postgres.password
    azure-blob:
      protocol: https
      host: mcpreports9276621.blob.core.windows.net
      port: 443
      auth:
        type: sas-token
        secret: azure.sas_token
    slack-webhook:
      protocol: https
      host: hooks.slack.com
      port: 443
      auth:
        type: webhook-url
        secret: slack.webhook_url
