name: cluster-health-reporter
version: "1.0"
description: "Generate daily cluster health report from Postgres data and send to Slack"

deployment:
  namespace: pd-cluster-health

triggers:
  - type: manual
  - type: cron
    name: daily-report
    schedule: "0 15 * * *"

nodes:
  query-health-history:
    path: ./nodes/query-health-history.ts
  analyze-trends:
    path: ./nodes/analyze-trends.ts
  send-report:
    path: ./nodes/send-report.ts

edges:
  - from: query-health-history
    to: analyze-trends
  - from: analyze-trends
    to: send-report

config:
  timeout: 120s
  retries: 1

contract:
  version: "1"
  dependencies:
    postgres:
      protocol: postgresql
      host: postgres-postgresql.postgres.svc.cluster.local
      port: 5432
      database: appdb
      user: postgres
      auth:
        type: password
        secret: postgres.password
    anthropic:
      protocol: https
      host: api.anthropic.com
      port: 443
      auth:
        type: api-key
        secret: anthropic.api_key
    slack:
      protocol: https
      host: hooks.slack.com
      port: 443
      auth:
        type: webhook-url
        secret: slack.webhook_url
